name: Scrape source

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 6-19 * * *'

jobs:
  convert:
    name: Convert data
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm ci

      - name: Execute converter
        run: |
          node convert.js

      - name: Check if the data changed
        id: update-required
        continue-on-error: true
        run: |
          echo "##[set-output name=changes;]$(git diff --name-only -- . | wc -l)"
          git diff --exit-code data.json corona-testungen-muenster-extracted.json

      - name: Update gh-pages branch
        if: steps.update-required.outputs.changes != '0'
        run: |
          mv corona-testungen-muenster-extracted.json /tmp/corona-testungen-muenster-geo.json
          # checkout gh-pages branch
          git remote set-branches --add origin gh-pages
          git fetch
          git checkout -t origin/gh-pages

          mv /tmp/corona-testungen-muenster-geo.json corona-testungen-muenster-geo.json
          d=$(TZ='Europe/Berlin' date +"%d.%m.%Y %H:%M")
          sed -i "s|<time datetime=.*|<time datetime=\"$(date -Iseconds)\">$d</time>|" index.html

          # add everything
          git add -A

          # tell git who you are
          git config user.name "GitHub-CI"
          git config user.email "actions-user@github.com"

          # commit
          git commit -m "map update for ${{ steps.version_info.outputs.version }} by GitHub Actions"

          # push to github
          git push "https://${{ github.token }}@github.com/${{ github.repository }}.git" gh-pages
