name: Scrape source

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 6-19 * * *'

jobs:
  staging:
    name: Scrape data
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm ci

      - name: Execute scraper
        run: |
          node scrape.js

      - name: Check if the data changed
        run: |
          git diff --exit-code data.json
