name:

on:
  push:
    branches:
      - main
#  schedule:
#    - cron: '30 6-19 * * 1-5'

jobs:
  staging:
    name: Scrape data
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies (TODO add package caching)
        run: |
          pip install -r requirements.txt

      - name: Execute scraper
        run: |
          python scrape.py
