name: Scrape source

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  convert:
    name: Convert data
    runs-on: ubuntu-20.04
    steps:
      - name: Debug
        run: |
           echo "github.ref is '${{ github.ref }}'"

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm ci --production

      - name: Execute converter
        run: |
          node convert.js

      - name: Prepare gh-pages branch
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          mv corona-testungen-muenster-extracted.json /tmp/corona-testungen-muenster-geo.json
          # checkout gh-pages branch
          git remote set-branches --add origin gh-pages
          git fetch
          git checkout -t origin/gh-pages

          # tell git who you are
          git config user.name "GitHub-CI"
          git config user.email "actions-user@github.com"


      - name: Check if the data changed
        if: ${{ github.ref == 'refs/heads/main' }}
        id: update-required
        continue-on-error: true
        run: |
          mv /tmp/corona-testungen-muenster-geo.json corona-testungen-muenster-geo.json
          echo "##[set-output name=changes;]$(git diff --name-only -- . | wc -l)"
          git diff --exit-code corona-testungen-muenster-geo.json

      - name: Update gh-pages branch
        if: ${{ github.ref == 'refs/heads/main' && steps.update-required.outputs.changes != '0' }}
        run: |
          d=$(TZ='Europe/Berlin' date +"%d.%m.%Y %H:%M")
          sed -i "s|<time datetime=.*|<time datetime=\"$(date -Iseconds)\">$d</time>|" index.html

          # add everything
          git add -A

          # commit
          git commit -m "map update for ${{ steps.version_info.outputs.version }} by GitHub Actions"

          # push to github
          git push "https://${{ github.token }}@github.com/${{ github.repository }}.git" gh-pages
